# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         News-Pan
version:      1.02
version_from: lib/News/Pan/Server.pm
installdirs:  site
requires:
    LEOCHARRE::CLI:                0
    LEOCHARRE::DEBUG:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
